on:
  push

name: Create jira issue

jobs:
  Create-jira-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: PA
        issuetype: Bug
        summary: |
          "${{ github.event.issue.title }}"
        description: |
          Compare branch

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"


   
