name: docker image

on:
  push:
    branches:
      - 'master'

jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          path: action
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: ./action
        with:
          file: ./Dockerfile
